CREATE TABLE [Account](
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[Key] VARCHAR(300) UNIQUE NOT NULL,
[UserName] VARCHAR(500) UNIQUE NOT NULL,
[Password] VARCHAR(100) NOT NULL,
[Email] VARCHAR(500) UNIQUE NOT NULL,
[ValidLogin] BIT NOT NULL,
[CreateDate] DATETIME NOT NULL
);

CREATE TABLE [Application](
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL, 
[Key] VARCHAR(300) UNIQUE NOT NULL,
[Redirect URL] VARCHAR(500) NOT NULL,
[Site] VARCHAR(100) NOT NULL,
);

CREATE TABLE [IP] (
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[Adress] VARCHAR(89) UNIQUE NOT NULL,
[Confiance] INT NOT NULL,
[AlreadyBeenBanned] BIT NOT NULL
);

CREATE TABLE [LoginFirstStep](
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL, 
[Date] DATETIME NOT NULL,
[Account] INTEGER NOT NULL,
[Token] VARCHAR(300) NOT NULL,
[IPAdress] VARCHAR(89) NOT NULL,
FOREIGN KEY ([IPAdress]) REFERENCES [IP]([Adress]),
FOREIGN KEY ([Account]) REFERENCES [Account]([ID])
);

CREATE TABLE [Authentication] (
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL,
[User-Agent] VARCHAR(300) NOT NULL,
[IPAdress] VARCHAR(89) NOT NULL,
[Token] VARCHAR(86) UNIQUE NOT NULL,
[LoginFirstStep] INTEGER NOT NULL,
[Date] DATETIME NOT NULL,
FOREIGN KEY ([LoginFirstStep]) REFERENCES [LoginFirstStep]([ID]),
FOREIGN KEY ([IPAdress]) REFERENCES [IP]([Adress])
);

CREATE TABLE [Authorization](
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL, 
[Authentication] INTEGER NOT NULL,
[Application] INTEGER NOT NULL,
[Level] INT NOT NULL,
[Date] DATETIME NOT NULL,
FOREIGN KEY ([Authentication]) REFERENCES [Authentication]([ID]),
FOREIGN KEY ([Application]) REFERENCES [Application]([ID])
);

CREATE TABLE [FailAttemp](
[ID] INTEGER IDENTITY PRIMARY KEY NOT NULL, 
[Date] DATETIME NOT NULL,
[IPAdress] VARCHAR(89) NOT NULL,
[AttempType] INT NOT NULL,
FOREIGN KEY ([IPAdress]) REFERENCES [IP]([Adress])
);
