//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuth.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authorization
    {
        public int ID { get; set; }
        public int Account { get; set; }
        public int Application { get; set; }
        public int Level { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Account Account1 { get; set; }
        public virtual Application Application1 { get; set; }
    }
}
