//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuth.Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginFirstStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoginFirstStep()
        {
            this.Authentication = new HashSet<Authentication>();
        }
    
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Account { get; set; }
        public string Token { get; set; }
        public string IPAdress { get; set; }
        public bool Valid { get; set; }
    
        public virtual Account Account1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Authentication> Authentication { get; set; }
    }
}
