//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAuth.Server.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OAuthEntities : DbContext
    {
        public OAuthEntities()
            : base("name=OAuthEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Authentication> Authentication { get; set; }
        public virtual DbSet<Authorization> Authorization { get; set; }
        public virtual DbSet<IP> IP { get; set; }
        public virtual DbSet<LoginFirstStep> LoginFirstStep { get; set; }
        public virtual DbSet<FailAttemp> FailAttemp { get; set; }
    }
}
